from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.cloud """
import os
import json
from ust.core.registry import skill

@skill(
    name="upload_to_s3",
    branch="cloud",
    description="Upload un fichier vers Amazon S3",
    parameters={
    "properties": {
        "file_path": {
            "type": "string"
        },
        "bucket": {
            "type": "string"
        },
        "key": {
            "type": "string"
        }
    },
    "required": [
        "file_path",
        "bucket",
        "key"
    ]
},
)
def upload_to_s3(file_path: str, bucket: str, key: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("AWS_ACCESS_KEY_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_ACCESS_KEY_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_SECRET_ACCESS_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_SECRET_ACCESS_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_DEFAULT_REGION"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_DEFAULT_REGION). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import boto3
        s3 = boto3.client("s3")
        s3.upload_file(file_path, bucket, key)
        return f"Uploadé : s3://{bucket}/{key}"
    except ImportError as e:
        reqs_str = " ".join(['boto3']) if ['boto3'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="download_from_s3",
    branch="cloud",
    description="Télécharge un fichier depuis Amazon S3",
    parameters={
    "properties": {
        "bucket": {
            "type": "string"
        },
        "key": {
            "type": "string"
        },
        "output": {
            "type": "string"
        }
    },
    "required": [
        "bucket",
        "key",
        "output"
    ]
},
)
def download_from_s3(bucket: str, key: str, output: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("AWS_ACCESS_KEY_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_ACCESS_KEY_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_SECRET_ACCESS_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_SECRET_ACCESS_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_DEFAULT_REGION"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_DEFAULT_REGION). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import boto3
        s3 = boto3.client("s3")
        s3.download_file(bucket, key, output)
        return f"Téléchargé : {output}"
    except ImportError as e:
        reqs_str = " ".join(['boto3']) if ['boto3'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="list_s3_files",
    branch="cloud",
    description="Liste les fichiers d'un bucket S3",
    parameters={
    "properties": {
        "bucket": {
            "type": "string"
        },
        "prefix": {
            "type": "string"
        }
    },
    "required": [
        "bucket"
    ]
},
)
def list_s3_files(bucket: str, prefix: str = "") -> list:
    # --- P&P Checks ---
    if not os.getenv("AWS_ACCESS_KEY_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_ACCESS_KEY_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_SECRET_ACCESS_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_SECRET_ACCESS_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("AWS_DEFAULT_REGION"):
        raise ValueError("Erreur Plug & Play : clé API manquante (AWS_DEFAULT_REGION). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import boto3
        s3 = boto3.client("s3")
        r = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)
        return [obj["Key"] for obj in r.get("Contents", [])]
    except ImportError as e:
        reqs_str = " ".join(['boto3']) if ['boto3'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="upload_to_gdrive",
    branch="cloud",
    description="Upload un fichier vers Google Drive",
    parameters={
    "properties": {
        "file_path": {
            "type": "string"
        },
        "folder_id": {
            "type": "string"
        }
    },
    "required": [
        "file_path"
    ]
},
)
def upload_to_gdrive(file_path: str, folder_id: str = None) -> str:
    # --- P&P Checks ---
    if not os.getenv("GOOGLE_CREDENTIALS_PATH"):
        raise ValueError("Erreur Plug & Play : clé API manquante (GOOGLE_CREDENTIALS_PATH). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
        from google.oauth2.credentials import Credentials
        import os
        creds = Credentials.from_authorized_user_file(os.getenv("GOOGLE_CREDENTIALS_PATH"))
        service = build("drive", "v3", credentials=creds)
        meta = {"name": os.path.basename(file_path)}
        if folder_id:
            meta["parents"] = [folder_id]
        media = MediaFileUpload(file_path, resumable=True)
        f = service.files().create(body=meta, media_body=media, fields="id").execute()
        return f"Fichier uploadé sur Drive, ID: {f.get('id')}"
    except ImportError as e:
        reqs_str = " ".join(['google-api-python-client', 'google-auth-oauthlib']) if ['google-api-python-client', 'google-auth-oauthlib'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="upload_to_dropbox",
    branch="cloud",
    description="Upload un fichier vers Dropbox",
    parameters={
    "properties": {
        "file_path": {
            "type": "string"
        },
        "dest_path": {
            "type": "string"
        }
    },
    "required": [
        "file_path",
        "dest_path"
    ]
},
)
def upload_to_dropbox(file_path: str, dest_path: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("DROPBOX_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (DROPBOX_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import dropbox
        dbx = dropbox.Dropbox(os.getenv("DROPBOX_TOKEN"))
        with open(file_path, "rb") as f:
            dbx.files_upload(f.read(), dest_path, mute=True)
        return f"Uploadé sur Dropbox : {dest_path}"
    except ImportError as e:
        reqs_str = " ".join(['dropbox']) if ['dropbox'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="create_cloudflare_kv",
    branch="cloud",
    description="Stocke une valeur dans Cloudflare KV",
    parameters={
    "properties": {
        "key": {
            "type": "string"
        },
        "value": {
            "type": "string"
        }
    },
    "required": [
        "key",
        "value"
    ]
},
)
def create_cloudflare_kv(key: str, value: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("CF_ACCOUNT_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (CF_ACCOUNT_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("CF_API_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (CF_API_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("CF_KV_NAMESPACE_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (CF_KV_NAMESPACE_ID). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        url = f"https://api.cloudflare.com/client/v4/accounts/{os.getenv('CF_ACCOUNT_ID')}/storage/kv/namespaces/{os.getenv('CF_KV_NAMESPACE_ID')}/values/{key}"
        r = requests.put(url, data=value, headers={"Authorization": f"Bearer {os.getenv('CF_API_TOKEN')}"})
        return f"KV créé (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="firebase_write",
    branch="cloud",
    description="Écrit des données dans Firebase Realtime Database",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "data": {
            "type": "object"
        }
    },
    "required": [
        "path",
        "data"
    ]
},
)
def firebase_write(path: str, data: dict) -> str:
    # --- P&P Checks ---
    if not os.getenv("FIREBASE_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (FIREBASE_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("FIREBASE_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (FIREBASE_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        url = f"{os.getenv('FIREBASE_URL')}/{path}.json?auth={os.getenv('FIREBASE_SECRET')}"
        r = requests.put(url, json=data)
        return f"Firebase écrit (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="firebase_read",
    branch="cloud",
    description="Lit des données depuis Firebase Realtime Database",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def firebase_read(path: str) -> dict:
    # --- P&P Checks ---
    if not os.getenv("FIREBASE_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (FIREBASE_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("FIREBASE_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (FIREBASE_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        url = f"{os.getenv('FIREBASE_URL')}/{path}.json?auth={os.getenv('FIREBASE_SECRET')}"
        return requests.get(url).json()
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="pinecone_upsert",
    branch="cloud",
    description="Insère des vecteurs dans Pinecone (base de données vectorielle)",
    parameters={
    "properties": {
        "vectors": {
            "type": "array"
        }
    },
    "required": [
        "vectors"
    ]
},
)
def pinecone_upsert(vectors: list) -> str:
    # --- P&P Checks ---
    if not os.getenv("PINECONE_API_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (PINECONE_API_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("PINECONE_INDEX"):
        raise ValueError("Erreur Plug & Play : clé API manquante (PINECONE_INDEX). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import pinecone
        pinecone.init(api_key=os.getenv("PINECONE_API_KEY"))
        index = pinecone.Index(os.getenv("PINECONE_INDEX"))
        index.upsert(vectors=vectors)
        return f"{len(vectors)} vecteurs insérés"
    except ImportError as e:
        reqs_str = " ".join(['pinecone-client']) if ['pinecone-client'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="supabase_insert",
    branch="cloud",
    description="Insère une ligne dans une table Supabase",
    parameters={
    "properties": {
        "table": {
            "type": "string"
        },
        "data": {
            "type": "object"
        }
    },
    "required": [
        "table",
        "data"
    ]
},
)
def supabase_insert(table: str, data: dict) -> dict:
    # --- P&P Checks ---
    if not os.getenv("SUPABASE_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (SUPABASE_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("SUPABASE_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (SUPABASE_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from supabase import create_client
        sb = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))
        return sb.table(table).insert(data).execute().data
    except ImportError as e:
        reqs_str = " ".join(['supabase']) if ['supabase'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="supabase_select",
    branch="cloud",
    description="Lit des données depuis une table Supabase",
    parameters={
    "properties": {
        "table": {
            "type": "string"
        },
        "filters": {
            "type": "object"
        }
    },
    "required": [
        "table"
    ]
},
)
def supabase_select(table: str, filters: dict = {}) -> list:
    # --- P&P Checks ---
    if not os.getenv("SUPABASE_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (SUPABASE_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("SUPABASE_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (SUPABASE_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from supabase import create_client
        sb = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))
        query = sb.table(table).select("*")
        for k, v in filters.items():
            query = query.eq(k, v)
        return query.execute().data
    except ImportError as e:
        reqs_str = " ".join(['supabase']) if ['supabase'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


