from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.automation """
import os
import json
from ust.core.registry import skill

@skill(
    name="browser_open_url",
    branch="automation",
    description="Ouvre une URL avec Playwright (navigateur headless)",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "headless": {
            "type": "boolean"
        }
    },
    "required": [
        "url"
    ]
},
)
def browser_open_url(url: str, headless: bool = True) -> str:
    # --- P&P Checks ---
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=headless)
            page = browser.new_page()
            page.goto(url)
            title = page.title()
            browser.close()
        return f"Page ouverte : {title}"
    except ImportError as e:
        reqs_str = " ".join(['playwright']) if ['playwright'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="browser_screenshot_url",
    branch="automation",
    description="Prend un screenshot d'une page web avec Playwright",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "output": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def browser_screenshot_url(url: str, output: str = "page.png") -> str:
    # --- P&P Checks ---
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url)
            page.screenshot(path=output, full_page=True)
            browser.close()
        return f"Screenshot : {output}"
    except ImportError as e:
        reqs_str = " ".join(['playwright']) if ['playwright'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="browser_fill_form",
    branch="automation",
    description="Remplit et soumet un formulaire web avec Playwright",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "fields": {
            "type": "object"
        },
        "submit_selector": {
            "type": "string"
        }
    },
    "required": [
        "url",
        "fields"
    ]
},
)
def browser_fill_form(url: str, fields: dict, submit_selector: str = "button[type=submit]") -> str:
    # --- P&P Checks ---
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url)
            for selector, value in fields.items():
                page.fill(selector, value)
            page.click(submit_selector)
            page.wait_for_load_state("networkidle")
            result = page.title()
            browser.close()
        return f"Formulaire soumis, nouvelle page : {result}"
    except ImportError as e:
        reqs_str = " ".join(['playwright']) if ['playwright'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="browser_get_page_text",
    branch="automation",
    description="Extrait tout le texte visible d'une page via Playwright (JS rendu)",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def browser_get_page_text(url: str) -> str:
    # --- P&P Checks ---
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url)
            text = page.inner_text("body")
            browser.close()
        return text[:5000]
    except ImportError as e:
        reqs_str = " ".join(['playwright']) if ['playwright'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="browser_click_element",
    branch="automation",
    description="Clique sur un élément d'une page web via sélecteur CSS",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "selector": {
            "type": "string"
        }
    },
    "required": [
        "url",
        "selector"
    ]
},
)
def browser_click_element(url: str, selector: str) -> str:
    # --- P&P Checks ---
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url)
            page.click(selector)
            page.wait_for_load_state("networkidle")
            result = page.title()
            browser.close()
        return f"Cliqué, nouvelle page : {result}"
    except ImportError as e:
        reqs_str = " ".join(['playwright']) if ['playwright'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="schedule_task",
    branch="automation",
    description="Planifie l'exécution répétée d'une fonction Python",
    parameters={
    "properties": {
        "interval_seconds": {
            "type": "integer"
        },
        "function_code": {
            "type": "string"
        }
    },
    "required": [
        "interval_seconds",
        "function_code"
    ]
},
)
def schedule_task(interval_seconds: int, function_code: str) -> str:
    # --- P&P Checks ---
    try:
        import schedule, time, threading
        def job():
            exec(function_code)
        schedule.every(interval_seconds).seconds.do(job)
        def run():
            while True:
                schedule.run_pending()
                time.sleep(1)
        t = threading.Thread(target=run, daemon=True)
        t.start()
        return f"Tâche planifiée toutes les {interval_seconds}s"
    except ImportError as e:
        reqs_str = " ".join(['schedule']) if ['schedule'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="watch_file_changes",
    branch="automation",
    description="Surveille un dossier et déclenche une action à chaque modification",
    parameters={
    "properties": {
        "folder": {
            "type": "string"
        },
        "on_change_code": {
            "type": "string"
        }
    },
    "required": [
        "folder"
    ]
},
)
def watch_file_changes(folder: str, on_change_code: str = "print(event)") -> str:
    # --- P&P Checks ---
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
        import threading
        class Handler(FileSystemEventHandler):
            def on_any_event(self, event):
                exec(on_change_code)
        observer = Observer()
        observer.schedule(Handler(), folder, recursive=True)
        t = threading.Thread(target=observer.start, daemon=True)
        t.start()
        return f"Surveillance de {folder} démarrée"
    except ImportError as e:
        reqs_str = " ".join(['watchdog']) if ['watchdog'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="auto_click_gui",
    branch="automation",
    description="Automatise des clics GUI via coordonnées (PyAutoGUI)",
    parameters={
    "properties": {
        "x": {
            "type": "integer"
        },
        "y": {
            "type": "integer"
        },
        "clicks": {
            "type": "integer"
        },
        "interval": {
            "type": "number"
        }
    },
    "required": [
        "x",
        "y"
    ]
},
)
def auto_click_gui(x: int, y: int, clicks: int = 1, interval: float = 0.25) -> str:
    # --- P&P Checks ---
    try:
        import pyautogui
        pyautogui.click(x, y, clicks=clicks, interval=interval)
        return f"Cliqué {clicks}x en ({x},{y})"
    except ImportError as e:
        reqs_str = " ".join(['pyautogui']) if ['pyautogui'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="hotkey_press",
    branch="automation",
    description="Presse une combinaison de touches clavier",
    parameters={
    "properties": {
        "keys": {
            "type": "array"
        }
    },
    "required": [
        "keys"
    ]
},
)
def hotkey_press(keys: list) -> str:
    # --- P&P Checks ---
    try:
        import pyautogui
        pyautogui.hotkey(*keys)
        return f"Touches pressées : {'+'.join(keys)}"
    except ImportError as e:
        reqs_str = " ".join(['pyautogui']) if ['pyautogui'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="fill_pdf_form",
    branch="automation",
    description="Remplit les champs d'un formulaire PDF",
    parameters={
    "properties": {
        "pdf_path": {
            "type": "string"
        },
        "fields": {
            "type": "object"
        },
        "output": {
            "type": "string"
        }
    },
    "required": [
        "pdf_path",
        "fields",
        "output"
    ]
},
)
def fill_pdf_form(pdf_path: str, fields: dict, output: str) -> str:
    # --- P&P Checks ---
    try:
        import fitz
        doc = fitz.open(pdf_path)
        for page in doc:
            for widget in page.widgets():
                if widget.field_name in fields:
                    widget.field_value = fields[widget.field_name]
                    widget.update()
        doc.save(output)
        return f"PDF rempli : {output}"
    except ImportError as e:
        reqs_str = " ".join(['pymupdf']) if ['pymupdf'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


