from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.data """
import os
import json
from ust.core.registry import skill

@skill(
    name="parse_json",
    branch="data",
    description="Parse un string JSON",
    parameters={
    "properties": {
        "json_str": {
            "type": "string"
        }
    },
    "required": [
        "json_str"
    ]
},
)
def parse_json(json_str: str) -> dict:
    # --- P&P Checks ---
    try:
        import json
        return json.loads(json_str)
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


