from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.social """
import os
import json
from ust.core.registry import skill

@skill(
    name="tweet_post",
    branch="social",
    description="Poste un tweet via l'API Twitter/X",
    parameters={
    "properties": {
        "text": {
            "type": "string"
        }
    },
    "required": [
        "text"
    ]
},
)
def tweet_post(text: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("TWITTER_API_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (TWITTER_API_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("TWITTER_API_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (TWITTER_API_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("TWITTER_ACCESS_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (TWITTER_ACCESS_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("TWITTER_ACCESS_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (TWITTER_ACCESS_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import tweepy
        client = tweepy.Client(
            consumer_key=os.getenv("TWITTER_API_KEY"),
            consumer_secret=os.getenv("TWITTER_API_SECRET"),
            access_token=os.getenv("TWITTER_ACCESS_TOKEN"),
            access_token_secret=os.getenv("TWITTER_ACCESS_SECRET")
        )
        r = client.create_tweet(text=text)
        return f"Tweet posté, ID: {r.data['id']}"
    except ImportError as e:
        reqs_str = " ".join(['tweepy']) if ['tweepy'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="tweet_search",
    branch="social",
    description="Recherche des tweets récents sur un sujet",
    parameters={
    "properties": {
        "query": {
            "type": "string"
        },
        "max_results": {
            "type": "integer"
        }
    },
    "required": [
        "query"
    ]
},
)
def tweet_search(query: str, max_results: int = 10) -> list:
    # --- P&P Checks ---
    if not os.getenv("TWITTER_BEARER_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (TWITTER_BEARER_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import tweepy
        client = tweepy.Client(bearer_token=os.getenv("TWITTER_BEARER_TOKEN"))
        r = client.search_recent_tweets(query=query, max_results=max_results)
        return [t.text for t in (r.data or [])]
    except ImportError as e:
        reqs_str = " ".join(['tweepy']) if ['tweepy'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="reddit_post",
    branch="social",
    description="Poste sur Reddit via PRAW",
    parameters={
    "properties": {
        "subreddit": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "body": {
            "type": "string"
        }
    },
    "required": [
        "subreddit",
        "title",
        "body"
    ]
},
)
def reddit_post(subreddit: str, title: str, body: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("REDDIT_CLIENT_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_CLIENT_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("REDDIT_CLIENT_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_CLIENT_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("REDDIT_USERNAME"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_USERNAME). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("REDDIT_PASSWORD"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_PASSWORD). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import praw
        reddit = praw.Reddit(
            client_id=os.getenv("REDDIT_CLIENT_ID"),
            client_secret=os.getenv("REDDIT_CLIENT_SECRET"),
            username=os.getenv("REDDIT_USERNAME"),
            password=os.getenv("REDDIT_PASSWORD"),
            user_agent="UST Bot"
        )
        post = reddit.subreddit(subreddit).submit(title, selftext=body)
        return f"Posté sur r/{subreddit} : {post.url}"
    except ImportError as e:
        reqs_str = " ".join(['praw']) if ['praw'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="reddit_get_hot",
    branch="social",
    description="Récupère les posts populaires d'un subreddit",
    parameters={
    "properties": {
        "subreddit": {
            "type": "string"
        },
        "limit": {
            "type": "integer"
        }
    },
    "required": [
        "subreddit"
    ]
},
)
def reddit_get_hot(subreddit: str, limit: int = 10) -> list:
    # --- P&P Checks ---
    if not os.getenv("REDDIT_CLIENT_ID"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_CLIENT_ID). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("REDDIT_CLIENT_SECRET"):
        raise ValueError("Erreur Plug & Play : clé API manquante (REDDIT_CLIENT_SECRET). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import praw
        reddit = praw.Reddit(
            client_id=os.getenv("REDDIT_CLIENT_ID"),
            client_secret=os.getenv("REDDIT_CLIENT_SECRET"),
            user_agent="UST Bot"
        )
        return [{"title": p.title, "score": p.score, "url": p.url}
                for p in reddit.subreddit(subreddit).hot(limit=limit)]
    except ImportError as e:
        reqs_str = " ".join(['praw']) if ['praw'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="github_create_repo",
    branch="social",
    description="Crée un nouveau dépôt GitHub",
    parameters={
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "private": {
            "type": "boolean"
        }
    },
    "required": [
        "name"
    ]
},
)
def github_create_repo(name: str, description: str = "", private: bool = False) -> str:
    # --- P&P Checks ---
    if not os.getenv("GITHUB_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (GITHUB_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        r = requests.post("https://api.github.com/user/repos",
            json={"name": name, "description": description, "private": private},
            headers={"Authorization": f"token {os.getenv('GITHUB_TOKEN')}", "Accept": "application/vnd.github.v3+json"})
        return r.json().get("html_url", r.text)
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="github_push_file",
    branch="social",
    description="Push un fichier sur un repo GitHub via l'API",
    parameters={
    "properties": {
        "repo": {
            "type": "string"
        },
        "file_path": {
            "type": "string"
        },
        "content": {
            "type": "string"
        },
        "message": {
            "type": "string"
        }
    },
    "required": [
        "repo",
        "file_path",
        "content"
    ]
},
)
def github_push_file(repo: str, file_path: str, content: str, message: str = "UST commit") -> str:
    # --- P&P Checks ---
    if not os.getenv("GITHUB_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (GITHUB_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests, base64
        url = f"https://api.github.com/repos/{repo}/contents/{file_path}"
        headers = {"Authorization": f"token {os.getenv('GITHUB_TOKEN')}", "Accept": "application/vnd.github.v3+json"}
        existing = requests.get(url, headers=headers).json()
        sha = existing.get("sha")
        data = {"message": message, "content": base64.b64encode(content.encode()).decode()}
        if sha:
            data["sha"] = sha
        r = requests.put(url, json=data, headers=headers)
        return f"Fichier pushé (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="send_pushover_notification",
    branch="social",
    description="Envoie une notification push via Pushover (mobile)",
    parameters={
    "properties": {
        "title": {
            "type": "string"
        },
        "message": {
            "type": "string"
        }
    },
    "required": [
        "title",
        "message"
    ]
},
)
def send_pushover_notification(title: str, message: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("PUSHOVER_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (PUSHOVER_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("PUSHOVER_USER"):
        raise ValueError("Erreur Plug & Play : clé API manquante (PUSHOVER_USER). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        r = requests.post("https://api.pushover.net/1/messages.json", data={
            "token": os.getenv("PUSHOVER_TOKEN"),
            "user": os.getenv("PUSHOVER_USER"),
            "title": title,
            "message": message
        })
        return f"Pushover (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="rss_feed_read",
    branch="social",
    description="Lit un flux RSS et retourne les derniers articles",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "limit": {
            "type": "integer"
        }
    },
    "required": [
        "url"
    ]
},
)
def rss_feed_read(url: str, limit: int = 5) -> list:
    # --- P&P Checks ---
    try:
        import feedparser
        feed = feedparser.parse(url)
        return [{"title": e.title, "link": e.link, "published": e.get("published", "")}
                for e in feed.entries[:limit]]
    except ImportError as e:
        reqs_str = " ".join(['feedparser']) if ['feedparser'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


