from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.security """
import os
import json
from ust.core.registry import skill

@skill(
    name="generate_password",
    branch="security",
    description="Génère un mot de passe sécurisé",
    parameters={
    "properties": {
        "length": {
            "type": "integer"
        }
    }
},
)
def generate_password(length: int = 16) -> str:
    # --- P&P Checks ---
    try:
        import secrets, string
        alphabet = string.ascii_letters + string.digits + string.punctuation
        return ''.join(secrets.choice(alphabet) for i in range(length))
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


