from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.dev """
import os
import json
from ust.core.registry import skill

@skill(
    name="lint_python_code",
    branch="dev",
    description="Analyse la qualité d'un fichier Python (pylint)",
    parameters={
    "properties": {
        "file_path": {
            "type": "string"
        }
    },
    "required": [
        "file_path"
    ]
},
)
def lint_python_code(file_path: str) -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["pylint", file_path, "--output-format=text"], capture_output=True, text=True)
        return r.stdout or r.stderr
    except ImportError as e:
        reqs_str = " ".join(['pylint']) if ['pylint'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="format_python_code",
    branch="dev",
    description="Formate du code Python avec Black",
    parameters={
    "properties": {
        "file_path": {
            "type": "string"
        }
    },
    "required": [
        "file_path"
    ]
},
)
def format_python_code(file_path: str) -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["black", file_path], capture_output=True, text=True)
        return r.stdout + r.stderr
    except ImportError as e:
        reqs_str = " ".join(['black']) if ['black'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="run_pytest",
    branch="dev",
    description="Lance les tests pytest d'un projet",
    parameters={
    "properties": {
        "test_path": {
            "type": "string"
        },
        "verbose": {
            "type": "boolean"
        }
    }
},
)
def run_pytest(test_path: str = ".", verbose: bool = True) -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        args = ["pytest", test_path]
        if verbose:
            args.append("-v")
        r = subprocess.run(args, capture_output=True, text=True)
        return r.stdout + r.stderr
    except ImportError as e:
        reqs_str = " ".join(['pytest']) if ['pytest'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="git_commit_push",
    branch="dev",
    description="Stage, commit et push tous les changements Git",
    parameters={
    "properties": {
        "message": {
            "type": "string"
        },
        "branch": {
            "type": "string"
        }
    }
},
)
def git_commit_push(message: str = "UST auto-commit", branch: str = "main") -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        results = []
        for cmd in [
            ["git", "add", "-A"],
            ["git", "commit", "-m", message],
            ["git", "push", "origin", branch]
        ]:
            r = subprocess.run(cmd, capture_output=True, text=True)
            results.append(r.stdout or r.stderr)
        return "
    ".join(results)
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="git_status",
    branch="dev",
    description="Retourne le statut Git du dossier courant",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    }
},
)
def git_status(path: str = ".") -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["git", "-C", path, "status"], capture_output=True, text=True)
        return r.stdout
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="create_virtualenv",
    branch="dev",
    description="Crée un environnement virtuel Python",
    parameters={
    "properties": {
        "name": {
            "type": "string"
        }
    }
},
)
def create_virtualenv(name: str = "venv") -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["python", "-m", "venv", name], capture_output=True, text=True)
        return f"Virtualenv '{name}' créé" if r.returncode == 0 else r.stderr
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="install_package",
    branch="dev",
    description="Installe un ou plusieurs packages pip",
    parameters={
    "properties": {
        "packages": {
            "type": "array"
        }
    },
    "required": [
        "packages"
    ]
},
)
def install_package(packages: list) -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["pip", "install"] + packages, capture_output=True, text=True)
        return r.stdout or r.stderr
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="generate_requirements",
    branch="dev",
    description="Génère un fichier requirements.txt depuis pip freeze",
    parameters={
    "properties": {
        "output": {
            "type": "string"
        }
    }
},
)
def generate_requirements(output: str = "requirements.txt") -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(["pip", "freeze"], capture_output=True, text=True)
        with open(output, "w") as f:
            f.write(r.stdout)
        return f"requirements.txt généré : {len(r.stdout.splitlines())} packages"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="create_dockerfile",
    branch="dev",
    description="Génère un Dockerfile de base pour un projet Python",
    parameters={
    "properties": {
        "app_file": {
            "type": "string"
        },
        "python_version": {
            "type": "string"
        }
    }
},
)
def create_dockerfile(app_file: str = "main.py", python_version: str = "3.11") -> str:
    # --- P&P Checks ---
    try:
        content = f"FROM python:{python_version}-slim
    WORKDIR /app
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt
    COPY . .
    CMD ["python", "{app_file}"]
    "
        with open("Dockerfile", "w") as f:
            f.write(content)
        return "Dockerfile créé"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="docker_run",
    branch="dev",
    description="Lance un conteneur Docker",
    parameters={
    "properties": {
        "image": {
            "type": "string"
        },
        "command": {
            "type": "string"
        },
        "ports": {
            "type": "string"
        }
    },
    "required": [
        "image"
    ]
},
)
def docker_run(image: str, command: str = "", ports: str = "") -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        args = ["docker", "run", "-d"]
        if ports:
            args += ["-p", ports]
        args.append(image)
        if command:
            args += command.split()
        r = subprocess.run(args, capture_output=True, text=True)
        return r.stdout.strip() or r.stderr
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="convert_code_language",
    branch="dev",
    description="Convertit du code d'un langage à un autre via IA (OpenAI)",
    parameters={
    "properties": {
        "code": {
            "type": "string"
        },
        "from_lang": {
            "type": "string"
        },
        "to_lang": {
            "type": "string"
        }
    },
    "required": [
        "code",
        "from_lang",
        "to_lang"
    ]
},
)
def convert_code_language(code: str, from_lang: str, to_lang: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("OPENAI_API_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (OPENAI_API_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from openai import OpenAI
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        prompt = f"Convertis ce code {from_lang} en {to_lang}. Retourne uniquement le code, sans explications.
    {code}"
        r = client.chat.completions.create(model="gpt-4o-mini", messages=[{"role":"user","content":prompt}])
        return r.choices[0].message.content
    except ImportError as e:
        reqs_str = " ".join(['openai']) if ['openai'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="explain_code",
    branch="dev",
    description="Explique un bout de code en langage naturel (via IA)",
    parameters={
    "properties": {
        "code": {
            "type": "string"
        },
        "language": {
            "type": "string"
        }
    },
    "required": [
        "code"
    ]
},
)
def explain_code(code: str, language: str = "Python") -> str:
    # --- P&P Checks ---
    if not os.getenv("OPENAI_API_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (OPENAI_API_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from openai import OpenAI
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        prompt = f"Explique ce code {language} en français, simplement :
    {code}"
        r = client.chat.completions.create(model="gpt-4o-mini", messages=[{"role":"user","content":prompt}])
        return r.choices[0].message.content
    except ImportError as e:
        reqs_str = " ".join(['openai']) if ['openai'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


