from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.system """
import os
import json
from ust.core.registry import skill

@skill(
    name="get_cpu_usage",
    branch="system",
    description="Retourne l'utilisation CPU en %",
    parameters={},
)
def get_cpu_usage() -> float:
    # --- P&P Checks ---
    try:
        import psutil
        return psutil.cpu_percent(interval=1)
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_ram_usage",
    branch="system",
    description="Retourne l'utilisation RAM",
    parameters={},
)
def get_ram_usage() -> dict:
    # --- P&P Checks ---
    try:
        import psutil
        m = psutil.virtual_memory()
        return {"total_gb": round(m.total/1e9,2), "used_gb": round(m.used/1e9,2), "percent": m.percent}
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_disk_usage",
    branch="system",
    description="Retourne l'espace disque disponible",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    }
},
)
def get_disk_usage(path: str = "/") -> dict:
    # --- P&P Checks ---
    try:
        import psutil
        d = psutil.disk_usage(path)
        return {"total_gb": round(d.total/1e9,2), "used_gb": round(d.used/1e9,2), "free_gb": round(d.free/1e9,2), "percent": d.percent}
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="run_command",
    branch="system",
    description="Exécute une commande shell et retourne la sortie",
    parameters={
    "properties": {
        "command": {
            "type": "string"
        }
    },
    "required": [
        "command"
    ]
},
    requires_confirmation=True,
)
def run_command(command: str) -> str:
    # --- P&P Checks ---
    try:
        import subprocess
        r = subprocess.run(command, shell=True, capture_output=True, text=True)
        return r.stdout or r.stderr
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="list_processes",
    branch="system",
    description="Liste les processus actifs (top 20 par CPU)",
    parameters={},
)
def list_processes() -> list:
    # --- P&P Checks ---
    try:
        import psutil
        procs = []
        for p in psutil.process_iter(['pid','name','cpu_percent','memory_percent']):
            try:
                procs.append(p.info)
            except:
                pass
        return sorted(procs, key=lambda x: x['cpu_percent'] or 0, reverse=True)[:20]
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="kill_process",
    branch="system",
    description="Tue un processus par son PID",
    parameters={
    "properties": {
        "pid": {
            "type": "integer"
        }
    },
    "required": [
        "pid"
    ]
},
    requires_confirmation=True,
)
def kill_process(pid: int) -> str:
    # --- P&P Checks ---
    try:
        import psutil
        try:
            p = psutil.Process(pid)
            p.kill()
            return f"Processus {pid} tué"
        except Exception as e:
            return f"Erreur: {e}"
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_os_info",
    branch="system",
    description="Retourne les infos du système d'exploitation",
    parameters={},
)
def get_os_info() -> dict:
    # --- P&P Checks ---
    try:
        import platform
        return {
            "os": platform.system(),
            "version": platform.version(),
            "machine": platform.machine(),
            "processor": platform.processor(),
            "hostname": platform.node(),
            "python": platform.python_version()
        }
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_battery_status",
    branch="system",
    description="Retourne l'état de la batterie",
    parameters={},
)
def get_battery_status() -> dict:
    # --- P&P Checks ---
    try:
        import psutil
        b = psutil.sensors_battery()
        if not b:
            return {"error": "Pas de batterie détectée"}
        return {"percent": b.percent, "charging": b.power_plugged, "time_left_min": round(b.secsleft/60) if b.secsleft > 0 else "inconnu"}
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="screenshot",
    branch="system",
    description="Prend une capture d'écran et la sauvegarde",
    parameters={
    "properties": {
        "save_path": {
            "type": "string"
        }
    }
},
)
def screenshot(save_path: str = "screenshot.png") -> str:
    # --- P&P Checks ---
    try:
        from PIL import ImageGrab
        img = ImageGrab.grab()
        img.save(save_path)
        return f"Screenshot sauvegardé : {save_path}"
    except ImportError as e:
        reqs_str = " ".join(['pillow']) if ['pillow'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="set_clipboard",
    branch="system",
    description="Met du texte dans le presse-papier",
    parameters={
    "properties": {
        "text": {
            "type": "string"
        }
    },
    "required": [
        "text"
    ]
},
)
def set_clipboard(text: str) -> str:
    # --- P&P Checks ---
    try:
        import pyperclip
        pyperclip.copy(text)
        return "Texte copié dans le presse-papier"
    except ImportError as e:
        reqs_str = " ".join(['pyperclip']) if ['pyperclip'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_clipboard",
    branch="system",
    description="Lit le contenu du presse-papier",
    parameters={},
)
def get_clipboard() -> str:
    # --- P&P Checks ---
    try:
        import pyperclip
        return pyperclip.paste()
    except ImportError as e:
        reqs_str = " ".join(['pyperclip']) if ['pyperclip'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="open_url_browser",
    branch="system",
    description="Ouvre une URL dans le navigateur par défaut",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def open_url_browser(url: str) -> str:
    # --- P&P Checks ---
    try:
        import webbrowser
        webbrowser.open(url)
        return f"URL ouverte : {url}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="send_notification_desktop",
    branch="system",
    description="Envoie une notification desktop (Windows/Mac/Linux)",
    parameters={
    "properties": {
        "title": {
            "type": "string"
        },
        "message": {
            "type": "string"
        }
    },
    "required": [
        "title",
        "message"
    ]
},
)
def send_notification_desktop(title: str, message: str) -> str:
    # --- P&P Checks ---
    try:
        from plyer import notification
        notification.notify(title=title, message=message, timeout=5)
        return f"Notification envoyée : {title}"
    except ImportError as e:
        reqs_str = " ".join(['plyer']) if ['plyer'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_network_speed",
    branch="system",
    description="Retourne les stats réseau (bytes envoyés/reçus)",
    parameters={},
)
def get_network_speed() -> dict:
    # --- P&P Checks ---
    try:
        import psutil, time
        n1 = psutil.net_io_counters()
        time.sleep(1)
        n2 = psutil.net_io_counters()
        return {
            "download_kbps": round((n2.bytes_recv - n1.bytes_recv) / 1024, 2),
            "upload_kbps": round((n2.bytes_sent - n1.bytes_sent) / 1024, 2)
        }
    except ImportError as e:
        reqs_str = " ".join(['psutil']) if ['psutil'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="lock_screen",
    branch="system",
    description="Verrouille l'écran (Windows/Mac/Linux)",
    parameters={},
)
def lock_screen() -> str:
    # --- P&P Checks ---
    try:
        import platform, subprocess
        s = platform.system()
        if s == "Windows":
            subprocess.run(["rundll32.exe", "user32.dll,LockWorkStation"])
        elif s == "Darwin":
            subprocess.run(["pmset", "displaysleepnow"])
        else:
            subprocess.run(["xdg-screensaver", "lock"])
        return "Écran verrouillé"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


