from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.files """
import os
import json
from ust.core.registry import skill

@skill(
    name="read_file",
    branch="files",
    description="Lit le contenu d'un fichier texte",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def read_file(path: str) -> str:
    # --- P&P Checks ---
    try:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        except Exception as e:
            return f"ERROR: {e}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="write_file",
    branch="files",
    description="Écrit du texte dans un fichier",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "content": {
            "type": "string"
        },
        "append": {
            "type": "boolean"
        }
    },
    "required": [
        "path",
        "content"
    ]
},
)
def write_file(path: str, content: str, append: bool = False) -> str:
    # --- P&P Checks ---
    try:
        mode = "a" if append else "w"
        with open(path, mode, encoding="utf-8") as f:
            f.write(content)
        return f"Fichier écrit : {path}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="list_files",
    branch="files",
    description="Liste les fichiers d'un dossier",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "pattern": {
            "type": "string"
        }
    }
},
)
def list_files(path: str = ".", pattern: str = "*") -> list:
    # --- P&P Checks ---
    try:
        import glob
        return glob.glob(f"{path}/{pattern}")
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="search_in_files",
    branch="files",
    description="Cherche un texte dans tous les fichiers d'un dossier",
    parameters={
    "properties": {
        "folder": {
            "type": "string"
        },
        "search_text": {
            "type": "string"
        }
    },
    "required": [
        "folder",
        "search_text"
    ]
},
)
def search_in_files(folder: str, search_text: str) -> list:
    # --- P&P Checks ---
    try:
        import os
        results = []
        for root, _, files in os.walk(folder):
            for f in files:
                path = os.path.join(root, f)
                try:
                    with open(path, "r", encoding="utf-8", errors="ignore") as fp:
                        for i, line in enumerate(fp, 1):
                            if search_text.lower() in line.lower():
                                results.append({"file": path, "line": i, "content": line.strip()})
                except:
                    pass
        return results
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="read_pdf",
    branch="files",
    description="Extrait le texte d'un fichier PDF",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def read_pdf(path: str) -> str:
    # --- P&P Checks ---
    try:
        import fitz
        doc = fitz.open(path)
        return "\n".join([page.get_text() for page in doc])
    except ImportError as e:
        reqs_str = " ".join(['pymupdf']) if ['pymupdf'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="read_excel",
    branch="files",
    description="Lit un fichier Excel et retourne les données",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "sheet": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def read_excel(path: str, sheet: str = None) -> list:
    # --- P&P Checks ---
    try:
        import openpyxl
        wb = openpyxl.load_workbook(path)
        ws = wb[sheet] if sheet else wb.active
        return [[cell.value for cell in row] for row in ws.iter_rows()]
    except ImportError as e:
        reqs_str = " ".join(['openpyxl']) if ['openpyxl'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="read_csv",
    branch="files",
    description="Lit un fichier CSV et retourne les données",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def read_csv(path: str) -> list:
    # --- P&P Checks ---
    try:
        import csv
        with open(path, "r", encoding="utf-8") as f:
            return list(csv.DictReader(f))
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="write_csv",
    branch="files",
    description="Écrit des données dans un fichier CSV",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "data": {
            "type": "array"
        },
        "headers": {
            "type": "array"
        }
    },
    "required": [
        "path",
        "data",
        "headers"
    ]
},
)
def write_csv(path: str, data: list, headers: list) -> str:
    # --- P&P Checks ---
    try:
        import csv
        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=headers)
            w.writeheader()
            w.writerows(data)
        return f"CSV écrit : {path}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="compress_folder",
    branch="files",
    description="Compresse un dossier en ZIP",
    parameters={
    "properties": {
        "folder_path": {
            "type": "string"
        },
        "output_path": {
            "type": "string"
        }
    },
    "required": [
        "folder_path",
        "output_path"
    ]
},
)
def compress_folder(folder_path: str, output_path: str) -> str:
    # --- P&P Checks ---
    try:
        import shutil
        shutil.make_archive(output_path.replace(".zip",""), "zip", folder_path)
        return f"Archive créée : {output_path}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="extract_zip",
    branch="files",
    description="Extrait un fichier ZIP",
    parameters={
    "properties": {
        "zip_path": {
            "type": "string"
        },
        "extract_to": {
            "type": "string"
        }
    },
    "required": [
        "zip_path"
    ]
},
)
def extract_zip(zip_path: str, extract_to: str = ".") -> str:
    # --- P&P Checks ---
    try:
        import zipfile
        with zipfile.ZipFile(zip_path, "r") as z:
            z.extractall(extract_to)
        return f"Extrait dans : {extract_to}"
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="convert_image",
    branch="files",
    description="Convertit une image vers un autre format (PNG, JPEG, WEBP...)",
    parameters={
    "properties": {
        "input_path": {
            "type": "string"
        },
        "output_path": {
            "type": "string"
        }
    },
    "required": [
        "input_path",
        "output_path"
    ]
},
)
def convert_image(input_path: str, output_path: str) -> str:
    # --- P&P Checks ---
    try:
        from PIL import Image
        img = Image.open(input_path)
        img.save(output_path)
        return f"Image convertie : {output_path}"
    except ImportError as e:
        reqs_str = " ".join(['pillow']) if ['pillow'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="resize_image",
    branch="files",
    description="Redimensionne une image",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        },
        "width": {
            "type": "integer"
        },
        "height": {
            "type": "integer"
        },
        "output": {
            "type": "string"
        }
    },
    "required": [
        "path",
        "width",
        "height",
        "output"
    ]
},
)
def resize_image(path: str, width: int, height: int, output: str) -> str:
    # --- P&P Checks ---
    try:
        from PIL import Image
        img = Image.open(path).resize((width, height))
        img.save(output)
        return f"Image redimensionnée : {output}"
    except ImportError as e:
        reqs_str = " ".join(['pillow']) if ['pillow'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="pdf_to_images",
    branch="files",
    description="Convertit chaque page d'un PDF en image",
    parameters={
    "properties": {
        "pdf_path": {
            "type": "string"
        },
        "output_folder": {
            "type": "string"
        }
    },
    "required": [
        "pdf_path"
    ]
},
)
def pdf_to_images(pdf_path: str, output_folder: str = "pdf_pages") -> str:
    # --- P&P Checks ---
    try:
        import fitz, os
        from PIL import Image
        os.makedirs(output_folder, exist_ok=True)
        doc = fitz.open(pdf_path)
        for i, page in enumerate(doc):
            pix = page.get_pixmap()
            pix.save(f"{output_folder}/page_{i+1}.png")
        return f"{len(doc)} pages extraites dans {output_folder}"
    except ImportError as e:
        reqs_str = " ".join(['pymupdf', 'pillow']) if ['pymupdf', 'pillow'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_file_info",
    branch="files",
    description="Retourne les métadonnées d'un fichier",
    parameters={
    "properties": {
        "path": {
            "type": "string"
        }
    },
    "required": [
        "path"
    ]
},
)
def get_file_info(path: str) -> dict:
    # --- P&P Checks ---
    try:
        import os, datetime
        s = os.stat(path)
        return {
            "name": os.path.basename(path),
            "size_kb": round(s.st_size / 1024, 2),
            "created": str(datetime.datetime.fromtimestamp(s.st_ctime)),
            "modified": str(datetime.datetime.fromtimestamp(s.st_mtime)),
            "extension": os.path.splitext(path)[1]
        }
    except ImportError as e:
        reqs_str = " ".join([]) if [] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


