from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.web """
import os
import json
from ust.core.registry import skill

@skill(
    name="web_search_ddg",
    branch="web",
    description="Recherche sur DuckDuckGo (gratuit, sans API key)",
    parameters={
    "properties": {
        "query": {
            "type": "string"
        },
        "max_results": {
            "type": "integer"
        }
    },
    "required": [
        "query"
    ]
},
)
def web_search_ddg(query: str, max_results: int = 5) -> list:
    # --- P&P Checks ---
    try:
        from duckduckgo_search import DDGS
        with DDGS() as ddgs:
            return list(ddgs.text(query, max_results=max_results))
    except ImportError as e:
        reqs_str = " ".join(['duckduckgo-search']) if ['duckduckgo-search'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="web_search_google",
    branch="web",
    description="Recherche Google via SerpAPI",
    parameters={
    "properties": {
        "query": {
            "type": "string"
        }
    },
    "required": [
        "query"
    ]
},
)
def web_search_google(query: str) -> list:
    # --- P&P Checks ---
    if not os.getenv("SERPAPI_KEY"):
        raise ValueError("Erreur Plug & Play : clé API manquante (SERPAPI_KEY). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        from serpapi import GoogleSearch
        s = GoogleSearch({"q": query, "api_key": os.getenv("SERPAPI_KEY")})
        return s.get_dict().get("organic_results", [])
    except ImportError as e:
        reqs_str = " ".join(['google-search-results']) if ['google-search-results'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="scrape_webpage",
    branch="web",
    description="Extrait le texte d'une page web",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def scrape_webpage(url: str) -> str:
    # --- P&P Checks ---
    try:
        import requests
        from bs4 import BeautifulSoup
        r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")
        for tag in soup(["script","style","nav","footer"]):
            tag.decompose()
        return soup.get_text(separator="\n", strip=True)[:5000]
    except ImportError as e:
        reqs_str = " ".join(['requests', 'beautifulsoup4']) if ['requests', 'beautifulsoup4'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="download_file",
    branch="web",
    description="Télécharge un fichier depuis une URL",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "save_path": {
            "type": "string"
        }
    },
    "required": [
        "url",
        "save_path"
    ]
},
)
def download_file(url: str, save_path: str) -> str:
    # --- P&P Checks ---
    try:
        import requests
        r = requests.get(url, stream=True)
        with open(save_path, "wb") as f:
            for chunk in r.iter_content(8192):
                f.write(chunk)
        return f"Fichier téléchargé : {save_path}"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="check_website_status",
    branch="web",
    description="Vérifie si un site web est accessible",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def check_website_status(url: str) -> dict:
    # --- P&P Checks ---
    try:
        import requests, time
        start = time.time()
        try:
            r = requests.get(url, timeout=5)
            return {"status": r.status_code, "online": True, "response_ms": round((time.time()-start)*1000)}
        except:
            return {"status": None, "online": False, "response_ms": None}
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_public_ip",
    branch="web",
    description="Retourne l'IP publique de la machine",
    parameters={},
)
def get_public_ip() -> str:
    # --- P&P Checks ---
    try:
        import requests
        return requests.get("https://api.ipify.org").text
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_geolocation",
    branch="web",
    description="Géolocalise une adresse IP",
    parameters={
    "properties": {
        "ip": {
            "type": "string"
        }
    }
},
)
def get_geolocation(ip: str = "auto") -> dict:
    # --- P&P Checks ---
    try:
        import requests
        url = f"https://ipapi.co/{ip}/json/" if ip != "auto" else "https://ipapi.co/json/"
        return requests.get(url).json()
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="send_webhook",
    branch="web",
    description="Envoie une requête POST à un webhook",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        },
        "data": {
            "type": "object"
        }
    },
    "required": [
        "url",
        "data"
    ]
},
)
def send_webhook(url: str, data: dict) -> str:
    # --- P&P Checks ---
    try:
        import requests
        r = requests.post(url, json=data)
        return f"Status: {r.status_code}"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_weather",
    branch="web",
    description="Météo d'une ville via Open-Meteo (gratuit, sans API key)",
    parameters={
    "properties": {
        "city": {
            "type": "string"
        }
    },
    "required": [
        "city"
    ]
},
)
def get_weather(city: str) -> dict:
    # --- P&P Checks ---
    try:
        import requests
        # Géocode d'abord
        geo = requests.get(f"https://geocoding-api.open-meteo.com/v1/search?name={city}&count=1").json()
        if not geo.get("results"):
            return {"error": f"Ville non trouvée : {city}"}
        r = geo["results"][0]
        lat, lon = r["latitude"], r["longitude"]
        w = requests.get(f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true").json()
        cw = w["current_weather"]
        return {"city": city, "temp_c": cw["temperature"], "wind_kmh": cw["windspeed"], "code": cw["weathercode"]}
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_crypto_price",
    branch="web",
    description="Retourne le prix d'une crypto en temps réel",
    parameters={
    "properties": {
        "symbol": {
            "type": "string"
        }
    }
},
)
def get_crypto_price(symbol: str = "bitcoin") -> dict:
    # --- P&P Checks ---
    try:
        import requests
        r = requests.get(f"https://api.coingecko.com/api/v3/simple/price?ids={symbol}&vs_currencies=usd,eur").json()
        return r.get(symbol, {"error": "Crypto non trouvée"})
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_stock_price",
    branch="web",
    description="Prix d'une action en temps réel via Yahoo Finance",
    parameters={
    "properties": {
        "ticker": {
            "type": "string"
        }
    },
    "required": [
        "ticker"
    ]
},
)
def get_stock_price(ticker: str) -> dict:
    # --- P&P Checks ---
    try:
        import yfinance as yf
        t = yf.Ticker(ticker)
        info = t.fast_info
        return {"ticker": ticker, "price": info.last_price, "currency": info.currency}
    except ImportError as e:
        reqs_str = " ".join(['yfinance']) if ['yfinance'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="translate_text",
    branch="web",
    description="Traduit un texte via Google Translate (gratuit)",
    parameters={
    "properties": {
        "text": {
            "type": "string"
        },
        "target_lang": {
            "type": "string"
        }
    },
    "required": [
        "text"
    ]
},
)
def translate_text(text: str, target_lang: str = "fr") -> str:
    # --- P&P Checks ---
    try:
        from deep_translator import GoogleTranslator
        return GoogleTranslator(source="auto", target=target_lang).translate(text)
    except ImportError as e:
        reqs_str = " ".join(['deep-translator']) if ['deep-translator'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="shorten_url",
    branch="web",
    description="Raccourcit une URL via TinyURL",
    parameters={
    "properties": {
        "url": {
            "type": "string"
        }
    },
    "required": [
        "url"
    ]
},
)
def shorten_url(url: str) -> str:
    # --- P&P Checks ---
    try:
        import requests
        r = requests.get(f"https://tinyurl.com/api-create.php?url={url}")
        return r.text
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="get_exchange_rate",
    branch="web",
    description="Taux de change entre deux devises",
    parameters={
    "properties": {
        "from_currency": {
            "type": "string"
        },
        "to_currency": {
            "type": "string"
        }
    }
},
)
def get_exchange_rate(from_currency: str = "USD", to_currency: str = "EUR") -> dict:
    # --- P&P Checks ---
    try:
        import requests
        r = requests.get(f"https://api.exchangerate-api.com/v4/latest/{from_currency}").json()
        rate = r["rates"].get(to_currency)
        return {"from": from_currency, "to": to_currency, "rate": rate}
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


