from __future__ import annotations

"""
  ⚠️ AUTO-GENERATED FILE ⚠️
  Do not edit this file directly!
  Please edit `skills_catalog.py` and run `python import_skills_catalog.py`.
"""
""" ust.skills.smarthome """
import os
import json
from ust.core.registry import skill

@skill(
    name="ha_get_states",
    branch="smarthome",
    description="Récupère les états de tous les appareils Home Assistant",
    parameters={},
)
def ha_get_states() -> list:
    # --- P&P Checks ---
    if not os.getenv("HA_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("HA_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        r = requests.get(f"{os.getenv('HA_URL')}/api/states",
            headers={"Authorization": f"Bearer {os.getenv('HA_TOKEN')}"})
        return r.json()
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="ha_turn_on",
    branch="smarthome",
    description="Allume un appareil Home Assistant (lumière, switch...)",
    parameters={
    "properties": {
        "entity_id": {
            "type": "string"
        }
    },
    "required": [
        "entity_id"
    ]
},
)
def ha_turn_on(entity_id: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("HA_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("HA_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        domain = entity_id.split(".")[0]
        r = requests.post(f"{os.getenv('HA_URL')}/api/services/{domain}/turn_on",
            headers={"Authorization": f"Bearer {os.getenv('HA_TOKEN')}"},
            json={"entity_id": entity_id})
        return f"Allumé : {entity_id} (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="ha_turn_off",
    branch="smarthome",
    description="Éteint un appareil Home Assistant",
    parameters={
    "properties": {
        "entity_id": {
            "type": "string"
        }
    },
    "required": [
        "entity_id"
    ]
},
)
def ha_turn_off(entity_id: str) -> str:
    # --- P&P Checks ---
    if not os.getenv("HA_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("HA_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests
        domain = entity_id.split(".")[0]
        r = requests.post(f"{os.getenv('HA_URL')}/api/services/{domain}/turn_off",
            headers={"Authorization": f"Bearer {os.getenv('HA_TOKEN')}"},
            json={"entity_id": entity_id})
        return f"Éteint : {entity_id} (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


@skill(
    name="ha_set_light_color",
    branch="smarthome",
    description="Change la couleur d'une lumière Home Assistant",
    parameters={
    "properties": {
        "entity_id": {
            "type": "string"
        },
        "rgb": {
            "type": "array"
        },
        "brightness": {
            "type": "integer"
        }
    },
    "required": [
        "entity_id",
        "rgb"
    ]
},
)
def ha_set_light_color(entity_id: str, rgb: list, brightness: int = 255) -> str:
    # --- P&P Checks ---
    if not os.getenv("HA_URL"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_URL). Ajoutez-la dans .env.ust puis réessayez.")
    if not os.getenv("HA_TOKEN"):
        raise ValueError("Erreur Plug & Play : clé API manquante (HA_TOKEN). Ajoutez-la dans .env.ust puis réessayez.")
    try:
        import requests, os
        domain = entity_id.split(".")[0]
        r = requests.post(f"{os.getenv('HA_URL')}/api/services/{domain}/turn_on",
            headers={"Authorization": f"Bearer {os.getenv('HA_TOKEN')}"},
            json={"entity_id": entity_id, "rgb_color": rgb, "brightness": brightness})
        return f"Couleur changée : {entity_id} (status {r.status_code})"
    except ImportError as e:
        reqs_str = " ".join(['requests']) if ['requests'] else str(e)
        raise ImportError("Erreur Plug & Play : package manquant. Demandez a utilisateur de lancer : pip install " + reqs_str)
    except Exception as e:
        raise e


